# Generated by Django 3.2 on 2021-04-28 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0002_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-send_time']},
        ),
    ]
